---
- hosts: checkpoint
  become: false
  gather_facts: false
  vars_files:
    - vault_prod.yml
    - fw_policy_changes.yml

  tasks:
  - name: "login to checkpoint MGT via the CheckPoint Module"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{ mgmt_user }}"
        password: "{{ mgmt_password }}"
        management: "{{ mgmt_server }}"
      fingerprint: "56:2B:FF:3C:A1:B2:38:29:E6:C6:47:FE:AA:08:D9:D9:54:66:62:12"
    register: login_response


  - name: Debug the fw_hosts and only run on debug tag.
    debug:
      msg: "These are the hosts we will add: {{ fw_hosts }}"
    tags:
      - debug
      - never
    when: add_new_host


  - name: "loop fw_hosts and add new host "
    check_point_mgmt:
      command: add-host
      parameters:
        name: "{{ item.name }}"
        ip-address: "{{ item.ip | ipaddr }}"
      session-data: "{{ login_response }}"
    loop: "{{ fw_hosts }}"
    when: add_new_host


  - name: "add new group '{{ host_group.name }}' with hosts"
    check_point_mgmt:
      command: add-group
      parameters:
        name: "{{ host_group.name }}"
        members: "{{ host_group.hosts}}"
      session-data: "{{ login_response }}"
    when: add_new_group


  - name: "create new tcp service '{{ tcp_service.name }}'"
    check_point_mgmt:
      command: add-service-tcp
      parameters:
        name: "{{ tcp_service.name }}"
        port: "{{ tcp_service.port }}"
      session-data: "{{ login_response }}"
    when: add_new_tcp_service


  - name: "create a section called {{ policy_section.name }}"
    check_point_mgmt:
      command: add-access-section
      parameters:
        layer: "{{ policy_section.layer }}"
        name: "{{ policy_section.name }}"
        position: "{{ policy_section.position }}"
      session-data: "{{ login_response }}"
    when: add_new_section


  - name: "create rule at the top of a section called '{{ fw_policy.name }}'"
    check_point_mgmt:
      command: add-access-rule
      parameters:
        layer: "{{ fw_policy.layer }}"
        name: "{{ fw_policy.name }}"
        position:
          below: "{{ fw_policy.position_below }}"
        source:
          - "{{ fw_policy.source }}"
        destination:
          - "{{ fw_policy.destination }}"
        service:
          - "{{ fw_policy.service }}"
        action: "{{ fw_policy.action }}"
        track:
          type: "{{ fw_policy.type }}"
      session-data: "{{ login_response }}"
    when: add_new_policy


  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{ login_response }}"


  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{ login_response }}"
