---
- hosts: checkpoint
  become: false
  gather_facts: false
  vars_files:
    - vault_prod.yml
    - fw_policy_changes.yml
  tasks:
  - name: "login to checkpoint MGT via the CheckPoint Module"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{ mgmt_user }}"
        password: "{{ mgmt_password }}"
        management: "{{ mgmt_server }}"
      fingerprint: "56:2B:FF:3C:A1:B2:38:29:E6:C6:47:FE:AA:08:D9:D9:54:66:62:12"
    register: login_response

  - name: "loop hosts and add new host '{{ item.name }}'"
    check_point_mgmt:
      command: add-host
      parameters:
        name: "{{ item.name }}"
        ip-address: "{{ item.ip | ipaddr }}"
      session-data: "{{ login_response }}"
    loop: "{{ fw.hosts }}"
    when: "{{ fw.add_new_host }}"

  - name: "add new group '{{ fw.group.name }}' with hosts"
    check_point_mgmt:
      command: add-group
      parameters:
        name: "{{ fw.group.name }}"
        members: {{ fw.group.hosts }}
      session-data: "{{ login_response }}"
    when: "{{ add_new_group }}"

  - name: "create new tcp service '{{ fw.tcp_service.name }}'"
    check_point_mgmt:
      command: add-service-tcp
      parameters:
        name: "{{ fw.tcp_service.name }}"
        port: "{{ fw.tcp_service.port }}"
      session-data: "{{ login_response }}"

  - name: "create a section called {{ fw.section.name }}"
    check_point_mgmt:
      command: add-access-section
      parameters:
        layer: "{{ fw.section.layer }}"
        name: "{{ fw.section.name }}"
        position: "{{ fw.section.position }}"
      session-data: "{{ login_response }}"

  - name: "create rule at the top of a section called '{{ fw.policy.name }}'"
    check_point_mgmt:
      command: add-access-rule
      parameters:
        layer: "{{ fw.policy.layer }}"
        name: "{{ fw.policy.name }}"
        position:
          below: "{{ fw.policy.position_below }}"
        source:
          - "{{ fw.policy.source }}"
        destination:
          - "{{ fw.policy.destination }}"
        service:
          - "{{ fw.policy.service }}"
        action: "{{ fw.policy.action }}"
        track:
          type: "{{ fw.policy.type }}"
      session-data: "{{ login_response }}"

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{ login_response }}"

  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{ login_response }}"
