---
  # configure file for websiteX
- name: Copy apache2.conf file
  copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf
  notify:
    - restart_apache_service

- name: Send index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart_apache_service
